# Generated by Django 5.2.4 on 2025-07-05 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bidding', '0001_initial'),
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='Job.job'),
        ),
    ]
