# Generated by Django 5.2.4 on 2025-08-04 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfiguration',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Platform fee as percentage of customer price', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
