# Generated by Django 5.2.4 on 2025-07-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_servicecategory_is_active_services_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, help_text='CSS color classes', max_length=50),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='tab_color',
            field=models.CharField(blank=True, help_text='CSS color classes for tabs', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price for the service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='color',
            field=models.CharField(blank=True, help_text='CSS color classes', max_length=50),
        ),
        migrations.AddField(
            model_name='services',
            name='estimated_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in hours', null=True),
        ),
    ]
