# Generated by Django 5.2.4 on 2025-08-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes about verification process'),
        ),
        migrations.AddField(
            model_name='driver',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', help_text='Driver verification status based on document verification', max_length=20),
        ),
    ]
