# Generated by Django 5.1.5 on 2025-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverdocument',
            name='document_file',
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='driver_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='driver_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
