# Generated by Django 5.1.5 on 2025-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0004_remove_driver_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_insurance_number',
            field=models.CharField(blank=True, help_text='National Insurance Number (e.g., AB123456C)', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_back',
            field=models.FileField(blank=True, null=True, upload_to='uploads/docs/drivers/%(driver_id)s/%(id)s/'),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_front',
            field=models.FileField(blank=True, null=True, upload_to='uploads/docs/drivers/%(driver_id)s/%(id)s/'),
        ),
    ]
