# Generated by Django 5.1.5 on 2025-06-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0005_alter_driver_national_insurance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='has_two_sides',
            field=models.BooleanField(default=False),
        ),
    ]
