# Generated by Django 5.1.5 on 2025-06-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0007_alter_driverdocument_document_back_and_more'),
        ('Driver', '0007_alter_driverdocument_document_fields'),
    ]

    operations = [
    ]
