# Generated by Django 5.1.5 on 2025-06-15 20:55

import apps.Driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0008_merge_20250615_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='document_back',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.Driver.models.DriverDocument.get_upload_path),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='document_front',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.Driver.models.DriverDocument.get_upload_path),
        ),
    ]
