# Generated by Django 5.1.5 on 2025-06-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0009_alter_driverdocument_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('verified', 'Verified'), ('pending', 'pending')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='verification_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
