# Generated by Django 5.2.4 on 2025-07-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0005_vehiclecategory_priority'),
        ('Location', '0001_initial'),
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicle',
            new_name='vehicle_vehicle_24f066_idx',
            old_name='vehicle_vehicle_6825ae_idx',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='clean_air_zone_status',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_refrigeration',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_tachograph',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_service_mileage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='load_height_mm',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='load_length_mm',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='load_width_mm',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mot_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='next_service_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='road_tax_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_interval_miles',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='service_interval_months',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='ulez_compliant',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vin',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_length_m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_lacation',
            field=models.ForeignKey(blank=True, help_text='where this is vehicle is based predominantely', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Location.location'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Vehicle model', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehicletype'),
        ),
    ]
