# Generated by Django 5.2.4 on 2025-07-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0002_rename_vehicle_vehicle_6825ae_idx_vehicle_vehicle_24f066_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='V5_Document',
            field=models.ImageField(blank=True, help_text='Optional: between log book, mot and V5', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='copy_of_MOT',
            field=models.ImageField(blank=True, help_text='Optional: between log book, mot and V5', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='copy_of_log_book',
            field=models.ImageField(blank=True, help_text='Optional: between log book, mot and V5', null=True, upload_to=''),
        ),
    ]
