# Generated by Django 5.2.4 on 2025-07-06 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0005_vehiclecategory_priority'),
        ('Vehicle', '0003_vehicle_v5_document_vehicle_copy_of_mot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehiclecategory'),
        ),
    ]
