# Generated by Django 5.2.4 on 2025-07-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0004_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'managed': True, 'ordering': ['provider', 'registration'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fleet_number',
        ),
    ]
