# Generated by Django 5.2.4 on 2025-07-06 22:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0005_alter_vehicle_options_remove_vehicle_fleet_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledocument',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicleinspection',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='V5_Document',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='copy_of_MOT',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='copy_of_log_book',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(help_text='UK Vehicle Registration Number (e.g., AB12 CDE, WK20 ABC, YK23 XYZ)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9 ]{1,10}$', 'Valid UK vehicle registration required')]),
        ),
        migrations.CreateModel(
            name='VehicleDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('log_book', 'Log Book'), ('mot', 'MOT Certificate'), ('v5', 'V5 Document'), ('insurance', 'Insurance Certificate'), ('service_book', 'Service Book'), ('other', 'Other Document')], max_length=20)),
                ('document', models.FileField(upload_to='vehicle_documents/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('expiry_date', models.DateField(blank=True, help_text='Document expiry date if applicable', null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Document',
                'verbose_name_plural': 'Vehicle Documents',
                'db_table': 'vehicle_documents',
                'ordering': ['vehicle', 'document_type', '-created_at'],
                'managed': True,
                'unique_together': {('vehicle', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='VehicleImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='vehicle_photos/%Y/%m/')),
                ('description', models.TextField(blank=True, help_text='Optional description of the photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (1-5)')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Vehicle.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Photo',
                'verbose_name_plural': 'Vehicle Photos',
                'db_table': 'vehicle_images',
                'ordering': ['vehicle', 'order', '-created_at'],
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='VehicleDocument',
        ),
        migrations.DeleteModel(
            name='VehicleInspection',
        ),
    ]
