# Generated by Django 5.2.4 on 2025-07-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0006_remove_vehicledocument_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='primary_lacation',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_location',
            field=models.JSONField(blank=True, help_text='Primary location where this vehicle is based', null=True),
        ),
    ]
