# Generated by Django 5.1.5 on 2025-06-16 00:20

import apps.Provider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0003_serviceprovider_bank_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerdocument',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Provider Document', 'verbose_name_plural': 'Provider Documents'},
        ),
        migrations.RenameField(
            model_name='providerdocument',
            old_name='upload_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='providerdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='providerdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.Provider.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='document_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.Provider.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='has_two_sides',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='providerdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='providerdocument',
            name='document_type',
            field=models.CharField(choices=[('driving_license', 'Driving License'), ('cpc_card', 'CPC Qualification Card'), ('tacho_card', 'Tachograph Card'), ('adr_certificate', 'ADR Certificate (Dangerous Goods)'), ('medical_certificate', 'Medical Certificate'), ('dbs_check', 'DBS Check Certificate'), ('driver_training', 'Driver Training Certificate'), ('passport', 'Passport/ID Document'), ('right_to_work', 'Right to Work Documentation'), ('proof_of_address', 'Proof of Address'), ('vehicle_registration', 'Vehicle Registration (V5C)'), ('mot_certificate', 'MOT Certificate'), ('vehicle_insurance', 'Vehicle Insurance Certificate'), ('operators_license', "Operator's License (O-License)"), ('plating_certificate', 'Plating Certificate (HGV)'), ('vehicle_inspection', 'Vehicle Inspection Certificate'), ('annual_test', 'Annual Test Certificate'), ('public_liability', 'Public Liability Insurance'), ('employers_liability', "Employer's Liability Insurance"), ('goods_in_transit', 'Goods in Transit Insurance'), ('professional_indemnity', 'Professional Indemnity Insurance'), ('motor_trade_insurance', 'Motor Trade Insurance'), ('company_registration', 'Company Registration Certificate'), ('vat_registration', 'VAT Registration Certificate'), ('trading_license', 'Trading License'), ('waste_carrier_license', 'Waste Carrier License'), ('scrap_metal_license', 'Scrap Metal Dealer License'), ('waste_management_license', 'Waste Management License'), ('health_safety_policy', 'Health & Safety Policy'), ('risk_assessment', 'Risk Assessment Document'), ('coshh_assessment', 'COSHH Assessment'), ('environmental_policy', 'Environmental Policy'), ('quality_management', 'Quality Management Certificate'), ('gdpr_policy', 'GDPR Privacy Policy'), ('bank_statement', 'Bank Statement'), ('financial_standing', 'Financial Standing Evidence'), ('credit_reference', 'Credit Reference'), ('employment_contract', 'Employment Contract'), ('contractor_agreement', 'Contractor Agreement'), ('terms_conditions', 'Terms & Conditions'), ('iso_certificate', 'ISO Certification'), ('bifa_membership', 'BIFA Membership Certificate'), ('fta_membership', 'FTA Membership Certificate'), ('trade_association', 'Trade Association Membership'), ('aea_certificate', 'AEA Certificate (Customs)'), ('eori_number', 'EORI Number Certificate'), ('customs_registration', 'Customs Registration'), ('other', 'Other Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='providerdocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['document_type'], name='provider_do_documen_0a9e03_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdocument',
            index=models.Index(fields=['status'], name='provider_do_status_310444_idx'),
        ),
    ]
