# Generated by Django 5.1.5 on 2025-06-16 00:40

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    InsurancePolicy = apps.get_model("Provider", "InsurancePolicy")
    ProviderDocument = apps.get_model("Provider", "ProviderDocument")
    ProviderPayment = apps.get_model("Provider", "ProviderPayment")
    ProviderReview = apps.get_model("Provider", "ProviderReview")
    ServiceArea = apps.get_model("Provider", "ServiceArea")

    for Model in [
        InsurancePolicy,
        ProviderDocument,
        ProviderPayment,
        ProviderReview,
        ServiceArea,
    ]:
        for row in Model.objects.all():
            row.new_id = uuid.uuid4()
            row.save(update_fields=["new_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("Provider", "0004_alter_providerdocument_options_and_more"),
    ]

    operations = [
        # Add created_at and updated_at fields
        migrations.AddField(
            model_name="insurancepolicy",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="insurancepolicy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="providerpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="providerreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # Add new UUID fields
        migrations.AddField(
            model_name="insurancepolicy",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="providerdocument",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="providerpayment",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="providerreview",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        # Generate UUIDs for existing records
        migrations.RunPython(gen_uuid),
        # Make new fields non-nullable and unique
        migrations.AlterField(
            model_name="insurancepolicy",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="providerdocument",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="providerpayment",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="providerreview",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name="servicearea",
            name="new_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        # Remove old primary keys
        migrations.RemoveField(
            model_name="insurancepolicy",
            name="id",
        ),
        migrations.RemoveField(
            model_name="providerdocument",
            name="id",
        ),
        migrations.RemoveField(
            model_name="providerpayment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="providerreview",
            name="id",
        ),
        migrations.RemoveField(
            model_name="servicearea",
            name="id",
        ),
        # Rename new fields to id
        migrations.RenameField(
            model_name="insurancepolicy",
            old_name="new_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="providerdocument",
            old_name="new_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="providerpayment",
            old_name="new_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="providerreview",
            old_name="new_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="servicearea",
            old_name="new_id",
            new_name="id",
        ),
        # Make new fields the primary keys
        migrations.AlterField(
            model_name="insurancepolicy",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="providerdocument",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="providerpayment",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="providerreview",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="servicearea",
            name="id",
            field=models.UUIDField(
                primary_key=True, default=uuid.uuid4, editable=False
            ),
        ),
    ]
