# Generated by Django 5.1.5 on 2025-06-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0003_initial'),
        ('Provider', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assigned_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='Provider.serviceprovider'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
