# Generated by Django 5.2.4 on 2025-08-17 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_initial'),
        ('Provider', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProviderAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_provider_links', to='Job.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_job_links', to='Provider.serviceprovider')),
            ],
            options={
                'verbose_name': 'Job Provider Acceptance',
                'verbose_name_plural': 'Job Provider Acceptances',
                'db_table': 'job_provider_acceptances',
                'managed': True,
                'unique_together': {('job', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='accepted_providers',
            field=models.ManyToManyField(blank=True, related_name='accepted_jobs', through='Job.JobProviderAcceptance', to='Provider.serviceprovider'),
        ),
    ]
