# Generated by Django 5.1.5 on 2025-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_number',
            field=models.CharField(blank=True, help_text='Unique job identifier with prefix', max_length=20, null=True, unique=True),
        ),
    ]
