# Generated by Django 5.1.5 on 2025-05-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='address_line1',
            field=models.CharField(default='acra', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='accra', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='county',
            field=models.CharField(default='eng', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='use_main_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
    ]
