# Generated by Django 5.1.5 on 2025-06-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0002_alter_location_options_location_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=30, null=True),
        ),
    ]
