# Generated by Django 5.2.4 on 2025-07-04 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CommonItems', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonitem',
            name='service_category',
            field=models.ForeignKey(blank=True, help_text='Service category for this category of items', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.servicecategory'),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.itemcategory'),
        ),
    ]
