# Generated by Django 5.2.4 on 2025-07-06 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the vehicle type', max_length=200)),
                ('description', models.CharField(help_text='The description for the vehicle type', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the vehicle category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the vehicle category')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100)),
                ('image', models.URLField(blank=True, help_text='URL to category image')),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('tab_color', models.CharField(blank=True, help_text='Hex color code for tabs', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Category is active and available')),
                ('vehicle_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehiclesize')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CommonItems.vehicletype')),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'db_table': 'vehicle_category',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
