# Generated by Django 5.2.4 on 2025-07-15 01:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonitem',
            options={'managed': True, 'ordering': ['category__name', 'type__name', 'brand__name', 'model__name', 'name'], 'verbose_name': 'Common Item', 'verbose_name_plural': 'Common Items'},
        ),
        migrations.AlterModelOptions(
            name='itembrand',
            options={'managed': True, 'ordering': ['category__name', 'type__name', 'name'], 'verbose_name': 'Item Brand', 'verbose_name_plural': 'Item Brands'},
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100)),
                ('image', models.URLField(blank=True, help_text='URL to type image')),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('tab_color', models.CharField(blank=True, help_text='Hex color code', max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Display priority order')),
                ('is_active', models.BooleanField(default=True, help_text='Type is active and available')),
                ('category', models.ForeignKey(help_text='Category this type belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='CommonItems.itemcategory')),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'db_table': 'item_type',
                'ordering': ['category__name', 'priority', 'name'],
                'managed': True,
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='commonitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itembrand',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type this item belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CommonItems.itemtype'),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type this brand belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='CommonItems.itemtype'),
        ),
        migrations.AlterUniqueTogether(
            name='commonitem',
            unique_together={('name', 'category', 'type', 'brand', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='itembrand',
            unique_together={('name', 'category', 'type')},
        ),
    ]
