# Generated by Django 5.2.4 on 2025-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0003_vehiclesize_vehicletype_vehiclecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesize',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclesize',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100),
        ),
        migrations.AddField(
            model_name='vehiclesize',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclesize',
            name='max_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum length in meters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiclesize',
            name='priority',
            field=models.IntegerField(default=0, help_text='Display priority order'),
        ),
        migrations.AddField(
            model_name='vehiclesize',
            name='tab_color',
            field=models.CharField(blank=True, help_text='Hex color code for tabs', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='icon',
            field=models.CharField(blank=True, help_text='FontAwesome icon name', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Display priority order'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='tab_color',
            field=models.CharField(blank=True, help_text='Hex color code for tabs', max_length=255),
        ),
    ]
