# Generated by Django 5.2.4 on 2025-08-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0003_alter_commonitem_options_alter_itembrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclesize',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Vehicle Size', 'verbose_name_plural': 'Vehicle Sizes'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
        migrations.AlterModelTable(
            name='vehiclesize',
            table='vehicle_size',
        ),
        migrations.AlterModelTable(
            name='vehicletype',
            table='vehicle_type',
        ),
    ]
