# Generated by Django 5.2.4 on 2025-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0004_vehiclesize_color_vehiclesize_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Display priority order'),
        ),
    ]
