# Generated by Django 5.1.5 on 2025-06-08 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_paymentmethod_options_alter_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Payment.payment')),
            ],
            options={
                'db_table': 'payment_event',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
