# Generated by Django 5.1.5 on 2025-05-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyStop', '0002_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeystop',
            name='address',
        ),
        migrations.AddField(
            model_name='journeystop',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Location.location'),
        ),
    ]
