# Generated by Django 5.1.5 on 2025-05-28 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JourneyStop", "0003_remove_journeystop_address_journeystop_location"),
        ("Location", "0002_alter_location_options_location_address_line1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journeystop",
            name="estimated_time",
        ),
        migrations.AlterField(
            model_name="journeystop",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stops",
                to="Location.location",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="journeystop",
            name="service_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
