# Generated by Django 5.1.5 on 2025-06-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyStop', '0004_remove_journeystop_estimated_time_and_more'),
        ('Location', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystop',
            name='location',
            field=models.ForeignKey(default='one off', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Location.location'),
            preserve_default=False,
        ),
    ]
