# Generated by Django 5.2.4 on 2025-08-17 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_loginsession_trusteddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
