# Generated by Django 5.2.4 on 2025-08-02 01:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_create_otp_and_userverification_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='otps_user_id_d6a90f_idx',
            old_name='otps_user_id_otp_typ_is_used_idx',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='otps_otp_cod_c4e311_idx',
            old_name='otps_otp_cod_expires_idx',
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
