# Generated by Django 5.2.4 on 2025-07-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='staff_required',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
