# Generated by Django 5.1.5 on 2025-06-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0003_alter_request_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
