# Generated by Django 5.1.5 on 2025-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0004_alter_request_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
